
steps:
  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/backend:$_STAGE',
           '--build-arg', 'REACT_APP_VERSION=$TAG_NAME',
           '--build-arg', 'GCP_PROJECT_ID=$PROJECT_ID',
           '--build-arg', 'REACT_APP_PROJECT_NAME=$_REACT_APP_PROJECT_NAME',
           '--build-arg', 'MONGO_DB_URL=$_MONGO_DB_URL',
           '--build-arg', 'MONGO_DB_DB_NAME=$_MONGO_DB_DB_NAME',
           '--build-arg', 'MONGO_DB_USER=$_MONGO_DB_USER',
           '--build-arg', 'MONGO_DB_PASS=$_MONGO_DB_PASS',
           '--build-arg', 'CRON_PASSWORD=$_CRON_PASSWORD',
           '--build-arg', 'GCP_SERVICE_ACCOUNT_EMAIL=$_GCP_SERVICE_ACCOUNT_EMAIL',
           '--build-arg', 'GCP_SERVICE_ACCOUNT_PRIVATE_KEY=$_GCP_SERVICE_ACCOUNT_PRIVATE_KEY',
           '--build-arg', 'GCP_ASSET_BUCKET=$_GCP_ASSET_BUCKET',
           '--build-arg', 'GCP_VIDEO_SOURCES_BUCKET=$_GCP_VIDEO_SOURCES_BUCKET',
           '--build-arg', 'ADMIN_INIT_USER=$_ADMIN_INIT_USER',
           '--build-arg', 'ADMIN_INIT_PASSWORD=$_ADMIN_INIT_PASSWORD',
           '--build-arg', 'REACT_APP_BACKEND_URL=$_REACT_APP_BACKEND_URL',
           '--build-arg', 'REACT_APP_ADMIN_URL=$_REACT_APP_ADMIN_URL',
           '--build-arg', 'REACT_APP_DOCS_URL=$_REACT_APP_DOCS_URL',
           '--build-arg', 'IOS_APP_SECRET=$_IOS_APP_SECRET',
           '--file', './backend/Dockerfile', '.']
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/admin:$_STAGE',
           '--build-arg', 'REACT_APP_VERSION=$TAG_NAME',
           '--build-arg', 'REACT_APP_PROJECT_NAME=$_REACT_APP_PROJECT_NAME',
           '--build-arg', 'REACT_APP_BACKEND_URL=$_REACT_APP_BACKEND_URL',
           '--build-arg', 'REACT_APP_ADMIN_URL=$_REACT_APP_ADMIN_URL',
           '--build-arg', 'REACT_APP_DOCS_URL=$_REACT_APP_DOCS_URL',
           '--file', './admin/Dockerfile', '.']
    id: 'build-admin'
    waitFor: ['-']

  # save
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/backend:$_STAGE']
    id: 'save-backend'
    waitFor:
      - 'build-backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/admin:$_STAGE']
    id: 'save-admin'
    waitFor:
      - 'build-admin'

  # deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'backend-$_STAGE', '--image', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/backend:$_STAGE', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
    waitFor:
      - 'save-backend'
      - 'save-admin'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'admin-$_STAGE', '--image', 'gcr.io/$PROJECT_ID/images/$TAG_NAME/admin:$_STAGE', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
    waitFor:
      - 'save-backend'
      - 'save-admin'

images:
  - gcr.io/$PROJECT_ID/images/$TAG_NAME/backend:$_STAGE
  - gcr.io/$PROJECT_ID/images/$TAG_NAME/admin:$_STAGE

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1200s