interface ValidateIOSReceiptResponse {
	environment: "SANDBOX" | "PRODUCTION",
	["is-retryable"]?: 0 | 1,
	latest_receipt?: string,
	latest_receipt_info?: LatestReceiptInfo[],
	pending_renewal_info?: PendingRenewalInfo[],
	receipt?: Receipt,
	status?: number;
}

interface LatestReceiptInfo {
	cancellation_date: string,
	cancellation_date_ms: string,
	cancellation_date_pst: string,
	cancellation_reason: "0" | "1",
	expires_date: string,
	expires_date_ms: string,
	expires_date_pst: string,
	in_app_ownership_type?: string,
	is_in_intro_offer_period: "true" | "false",
	is_trial_period: "true" | "false",
	is_upgraded?: "true",
	offer_code_ref_name?: string,
	original_purchase_date: string,
	original_purchase_date_ms: string,
	original_purchase_date_pst: string,
	original_transaction_id: string,
	product_id: string,
	promotional_offer_id?: string,
	purchase_date: string,
	purchase_date_ms: string,
	purchase_date_pst: string,
	quantity: string,
	subscription_group_identifier?: "",
	web_order_line_item_id: "",
	transaction_id: string,
}

interface PendingRenewalInfo {
	auto_renew_product_id?: string,
	auto_renew_status: "1" | "0",
	expiration_intent?: "1" | "2" | "3" | "4" | "5",
	grace_period_expires_date: string,
	grace_period_expires_date_ms: string,
	grace_period_expires_date_pst: string,
	is_in_billing_retry_period?: "1" | "0",
	offer_code_ref_name?: string,
	original_transaction_id: string,
	price_consent_status?: "1" | "0",
	product_id: string,
}

interface Receipt {
	adam_id: number,
	app_item_id: number,
	application_version: string,
	bundle_id: string,
	download_id: number,
	expiration_date: string,
	expiration_date_ms?: string,
	expiration_date_pst: string,
	in_app: InApp[],
	original_application_version: "1.0" | string,
	original_purchase_date: string,
	original_purchase_date_ms: string,
	original_purchase_date_pst: string,
	preorder_date: string,
	preorder_date_ms?: string,
	preorder_date_pst: string,
	receipt_creation_date: string,
	receipt_creation_date_ms: string,
	receipt_creation_date_pst: string,
	receipt_type: "Production" | "ProductionVPP" | "ProductionSandbox" | "ProductionVPPSandbox",
	request_date: string,
	request_date_pst: string,
	version_external_identifier: 0 | number,
}

interface InApp {
	cancellation_date: string,
	cancellation_date_ms: string,
	cancellation_date_pst: string,
	cancellation_reason: "0" | "1",
	expires_date: string,
	expires_date_ms: string,
	expires_date_pst: string,
	is_in_intro_offer_period?: "true" | "false",
	is_trial_period?: "true" | "false",
	original_purchase_date: string,
	original_purchase_date_ms: string,
	original_purchase_date_pst: string,
	original_transaction_id: string,
	product_id: string,
	promotional_offer_id: string,
	purchase_date: string,
	purchase_date_ms: string,
	purchase_date_pst: string,
	quantity: string,
	transaction_id: string,
	web_order_line_item_id: string,
}

export {ValidateIOSReceiptResponse, LatestReceiptInfo, PendingRenewalInfo, Receipt, InApp}