FROM node:14.4.0-alpine

# copy over the client files
WORKDIR /usr/src/client
COPY ./client/package*.json ./
RUN npm install

# install libraries
WORKDIR /usr/src/admin
COPY ./admin/package*.json ./
RUN npm install

# copy over all client files
WORKDIR /usr/src/client
COPY ./client ./

# copy over admin files
WORKDIR /usr/src/admin
RUN npm link ../client
COPY ./admin ./

EXPOSE 8080

CMD ["npm", "start"]