import "./forgot_password";
import "./sign_up";
import "./change_password";
import "./get_user_stats";
import "./user_login";
import "./update_name";
import "./forgot_password";
// import "./add_subscription";
import "./validate_ios_receipt";
import "./is_valid_ios_receipt";
import "./addIOSReceiptToUser";